version: '3'

services:
  web:
    image: nginx
    build:
      context: .
      dockerfile: ./nginx/Dockerfile
    environment:
      - NGINX_HOST=foobar.com
      - NGINX_PORT=80
    ports:
      - 80:80
    depends_on:
      - db
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: ""
    volumes:
      - ./postgres:/var/lib/postgresql/data
    ports:
      - 5432
  app:
    build: .
    volumes:
      - ./rails_app:/rails_app
    environment:
      - RAILS_ENV=${RAILS_ENV}
    depends_on:
      - db